Garage2/Models/Vehicle.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Garage2.Models
{
    public class Vehicle
    {
        public int Id { get; set; }

        [Display(Name = "Fordonstyp")]
        [Required]
        public VehicleTypes Type { get; set; }

        [Display(Name = "Registreringsnummer")]
        [RegularExpression(@"^[A-Za-z]{3}(\d{3})$", ErrorMessage="Felaktigt format. Förväntade AAA999")]
        [Required(ErrorMessage = "Registrerinsnummer saknas")]
        [StringLength(6)]
        public string RegNum { get; set; }

        [Display(Name = "Märke")]
        [StringLength(40)]
        public string Make { get; set; }

        [Display(Name = "Modell")]
        [StringLength(40)]
        public string Model { get; set; }

        [Display(Name = "Färg")]
        [StringLength(40)]
        public string Color { get; set; }

        [Display(Name = "Antal hjul")]
        [Required(ErrorMessage = "Antal hjul saknas")]
        [Range(0, 9999)]
        public int WheelCount { get; set; }

        [Display(Name = "Ankomsttid")]
        public DateTime ArrivalTime { get; set; }
    }
}

Garage2/Models/VehicleTypes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Garage2.Models
{
    public enum VehicleTypes
    {
        [Display(Name = "Flygplan")]
        Aeroplane,

        [Display(Name = "Båt")]
        Boat,

        [Display(Name = "Buss")]
        Bus,

        [Display(Name = "Bil")]
        Car,

        [Display(Name = "Motorcyckel")]
        Motorcycle
    }
}

Garage2/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Garage2.Models;
using Garage2.Configuration;
using System.Globalization;
using Garage2.Utilities;

namespace Garage2.Controllers
{
    public class VehiclesController : Controller
    {
        private GarageContext db = new GarageContext();

        // GET: Vehicles
        public ActionResult Index()
        {
            var param = Request["sortOrder"];
            var list = db.Vehicles.Select(v => v);

            if (param != null) { 
                switch (param.ToString())
                {
                    case "RegNum":
                        list = list.OrderBy(v => v.RegNum);
                        break;
                    case "Type":
                        list = list.OrderBy(v => v.Type.ToString());
                        break;
                    case "Make":
                        list = list.OrderBy(v => v.Make);
                        break;
                    case "Model":
                        list = list.OrderBy(v => v.Model);
                        break;
                    case "Color":
                        list = list.OrderBy(v => v.Color);
                        break;
                    case "ArrivalTime":
                        list = list.OrderBy(v => v.ArrivalTime);
                        break;
                    default:
                        list = list.OrderBy(v => v.RegNum);
                        break;
                }
            }
            return View(list.ToList()   );
        }

        // GET: Vehicles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // GET: Vehicles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vehicles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Type,RegNum,Make,Model,Color,WheelCount")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                bool valid = true;
                // Check if the same duplicate reg numbers exist with the same type
                var list =
                    db.Vehicles.Where(v => v.RegNum.Contains(vehicle.RegNum) && v.Type == vehicle.Type)
                        .Select(v => v)
                        .ToList();
                if (list.Count() > 0)
                {
                    valid = false;
                }

                // Check if duplicates exist within a category of vehicles
                if ((vehicle.Type == VehicleTypes.Bus) ||
                    (vehicle.Type == VehicleTypes.Car) ||
                    (vehicle.Type == VehicleTypes.Motorcycle))
                {
                    list =
                        db.Vehicles.Where(v => v.RegNum.Contains(vehicle.RegNum))
                            .Select(v => v)
                            .ToList();

                    if (list.Count > 0)
                    {
                        foreach (var item in list)
                        {
                            if ((item.Type == VehicleTypes.Bus) ||
                                (item.Type == VehicleTypes.Car) ||
                                (item.Type == VehicleTypes.Motorcycle))
                            {
                                valid = false;
                            }
                        }
                    }

                }

                if (valid)
                {
                    vehicle.ArrivalTime = DateTime.Now;
                    vehicle.RegNum = vehicle.RegNum.ToUpper();
                    db.Vehicles.Add(vehicle);
                    db.SaveChanges();
                }
                else
                {
                    ModelState.AddModelError("RegNum", "Fordon är redan parkerat");
                    return View("Create");
                }
                return RedirectToAction("Index");
            }

            return View(vehicle);
        }

        // GET: Vehicles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Type,RegNum,Make,Model,Color,WheelCount, ArrivalTime")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vehicle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vehicle);
        }

        // GET: Vehicles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = db.Vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, bool receipt = false)
        {

            Vehicle vehicle = db.Vehicles.Find(id);
            db.Vehicles.Remove(vehicle);
            db.SaveChanges();
            if (receipt == false)
            {
                return RedirectToAction("Index");
            }
            else
            {
                TempData["vehicle"] = vehicle;
                return RedirectToAction("Receipt");
            }

        }

        [HttpGet]
        public ActionResult Search()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search([Bind(Include = "RegNum")] SearchString str)
        {
            if (ModelState.IsValid)
            {
                if (!string.IsNullOrEmpty(str.RegNum))
                {
                    var list =
                        db.Vehicles.Where(v => v.RegNum.Contains(str.RegNum))
                            .Select(v => v)
                            .ToList();
                    if (list.Count() == 1)
                    {
                        Vehicle vehicle = list[0];
                        return View("Details", vehicle);
                    }
                    else if (list.Count > 1)
                    {
                        return View("Index", list);
                    }
                    else
                    {
                        ModelState.AddModelError("RegNum", "Fordonet hittades inte.");
                    }
                }
            }
            return View("Search");
        }


        // GET: Vehicles/Receipt/5

        public ActionResult Receipt()
        {
            Vehicle v = TempData["vehicle"] as Vehicle;
            ViewBag.RegNum = v.RegNum;
            ViewBag.ArrivalTime = v.ArrivalTime;
            ViewBag.Departure = DateTime.Now;

            TimeSpan Duration = ViewBag.Departure.Subtract(ViewBag.ArrivalTime);
            ViewBag.Duration = String.Format("{0} dagar, {1} timmar, {2} minuter", Duration.Days, Duration.Hours, Duration.Minutes);
            var price = Math.Floor(Duration.TotalMinutes * appSettings.PricePerMinute());
            ViewBag.TotalPrice = price.ToString("C",
                  CultureInfo.CreateSpecificCulture("sv-SE"));

            return View();
        }

        public ActionResult Statistics()
        {
            ViewBag.Tires = CalculateStatistics.CountTiresInDb(db.Vehicles.ToList());
            ViewBag.Types = CalculateStatistics.CountTypesInDb(db.Vehicles.ToList());
            ViewBag.Colors = CalculateStatistics.CountColorOfTypesInDb(db.Vehicles.ToList());
            ViewBag.Makes =  CalculateStatistics.CountMakeInDb(db.Vehicles.ToList());

            

            return View();
        }


        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Garage2/Views/Vehicles/Create.cshtml
@model Garage2.Models.Vehicle

@{
    ViewBag.Title = "Skapa";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Fordon</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Make, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Make, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Make, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WheelCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WheelCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WheelCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Skapa" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tillbaka", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Garage2/Views/Vehicles/Delete.cshtml
@model Garage2.Models.Vehicle

@{
    ViewBag.Title = "Kör ut";
}

<h2>@ViewBag.Title</h2>

<h3>Är du säker på att du vill köra ut detta fordon?</h3>
<div>
    <h4>Fordon</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Make)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Make)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="checkbox" value="true" name="receipt"/>
            <label>Kvitto på parkering</label><br />
            <input type="submit" value="Kör ut" class="btn btn-default" /> |
            @Html.ActionLink("Tillbaka", "Index")
        </div>
    }


  
</div>

Garage2/Views/Vehicles/Details.cshtml
@model Garage2.Models.Vehicle

@{
    ViewBag.Title = "Detaljer";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>Fordon</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ArrivalTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArrivalTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Make)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Make)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WheelCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WheelCount)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Redigera", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Tillbaka", "Index")
</p>

Garage2/Views/Vehicles/Edit.cshtml
@model Garage2.Models.Vehicle

@{
    ViewBag.Title = "Redigera";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Fordon</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.ArrivalTime)

       <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Type, new {@readonly = "readonly" , @class = "form-control"})
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.RegNum, new {@readonly = "readonly", @class = "form-control"})
                @Html.ValidationMessageFor(model => model.RegNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Make, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Make, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Make, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WheelCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WheelCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WheelCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spara" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tillbaka", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Garage2/Views/Vehicles/Index.cshtml
@model IEnumerable<Garage2.Models.Vehicle>

@{
    ViewBag.Title = "Garage 2.0";
}

<h2>Parkerade fordon</h2>

<p>
    @Html.ActionLink("Parkera fordon", "Create")
</p>
<table class="table display" id="sortTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RegNum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Make)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArrivalTime)
            </th>
            <th class="no-sort"></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RegNum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Make)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Model)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Color)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ArrivalTime)
                </td>
                <td>
                    @Html.ActionLink("Redigera", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Detaljer", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Kör ut", "Delete", new { id = item.Id })
                </td>
            </tr>

        }
    </tbody>
</table>


<div id="smallView">
    <form method="get">
        <select name="sortOrder" onchange="this.form.submit();">
            <option selected hidden>Välj sorteringsordning</option>
            <option value="RegNum">Registreringsnummer</option>
            <option value="Type">Fordonstyp</option>
            <option value="Make">Märke</option>
            <option value="Model">Modell</option>
            <option value="Color">Färg</option>
            <option value="ArrivalTime">Ankomstid</option>
        </select>
    </form>
   
    @foreach (var item in Model)
    {
        <div class="well well-sm">
            <ul class="list-unstyled">
                <li><strong>@Html.DisplayNameFor(model => model.RegNum): </strong>@Html.DisplayFor(modelItem => item.RegNum)</li>
                <li><strong>@Html.DisplayNameFor(model => model.Type):  </strong>@Html.DisplayFor(modelItem => item.Type)</li>
                <li><strong>@Html.DisplayNameFor(model => model.Make):  </strong>@Html.DisplayFor(modelItem => item.Make)</li>
                <li><strong>@Html.DisplayNameFor(model => model.Model):  </strong>@Html.DisplayFor(modelItem => item.Model)</li>
                <li><strong>@Html.DisplayNameFor(model => model.Color):  </strong>@Html.DisplayFor(modelItem => item.Color)</li>
                <li><strong>@Html.DisplayNameFor(model => model.ArrivalTime):  </strong>@Html.DisplayFor(modelItem => item.ArrivalTime)</li>
            </ul>
            @Html.ActionLink("Redigera", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Detaljer", "Details", new { id = item.Id }) |
            @Html.ActionLink("Kör ut", "Delete", new { id = item.Id })
        </div>

    }
</div>

Garage2/Views/Vehicles/Receipt.cshtml
@model Garage2.Models.Vehicle

@{
    ViewBag.Title = "Kvitto";
}




<div class="container">
    <h2>Kvitto för @ViewBag.RegNum</h2>

    <div class="well well-lg col-md-4">
        <table>
            <tr>
                <td>
                    <strong>Ankomsttid: </strong>
                </td>
                <td>
                    @ViewBag.ArrivalTime
                </td>
            </tr>
            <tr>
                <td>
                    <strong>Utresetid: </strong>
                </td>
                <td>
                    @ViewBag.Departure
                </td>
            </tr>
            <tr>
                <td>
                    <strong>Parkeringstid: </strong>
                </td>
                <td>
                    @ViewBag.Duration
                </td>
            </tr>

        </table>
        <hr />
        <strong>Total kostnad: </strong>@ViewBag.TotalPrice
    </div>
</div>    
@Html.ActionLink("Tillbaka", "Index")
           
       




    @*<td>
            @Html.ActionLink("Redigera", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Detaljer", "Details", new { id = item.Id }) |
            @Html.ActionLink("Kör ut", "Delete", new { id = item.Id })
        </td>*@

Garage2/Views/Vehicles/Search.cshtml
@model Garage2.Models.SearchString
@{
    ViewBag.Title = "Sök";
}
<h2>Sök på registreringsnummer</h2>
@using (Html.BeginForm("Search", "Vehicles", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Fordon</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.RegNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sök" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Tillbaka", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Garage2/Views/Vehicles/Statistics.cshtml
@model Garage2.Models.Vehicle

@{
    ViewBag.Title = "Statistics";
}

<h2>Statistics</h2>

<strong>Antal hjul i garaget: </strong>@ViewBag.Tires <br />
<hr />

<strong>Antal fordon i garaget</strong>
<ul class="list-unstyled">
    @foreach (var item in ViewBag.Types)
    {
        <li>
            @Html.Display(Model.GetDescription(Model.VehicleTypes.GetType(), Model.VehicleTypes))) : @item.Value
        </li>
    }
</ul>

<hr />

<strong>Antal färger i garaget</strong>
<ul class="list-unstyled">
    @foreach (var item in ViewBag.Colors)
    {
        <li>
            @item.Key: @item.Value
        </li>
    }
</ul>

<hr />

<strong>Antal märken i garaget</strong>
<ul class="list-unstyled">
    @foreach (var item in ViewBag.Makes)
    {
        <li>
            @item.Key: @item.Value
        </li>
    }
</ul>